databricks_resources:
  model_name: "databricks-claude-3-7-sonnet"
  vs_index_endpoint_name: "one-env-shared-endpoint-13"
  
retriever_config:
  index_name: global_fs.worldbank.chapter_index
  columns: 
    - chapter
    - chapter_text
    - footnotes
  parameters: 
    k: 1
  retriever_schema:
    primary_key: chapter
    text_column: chapter_text
    doc_uri: chapter
    name: databricks_documentation_vs_index

llm_config:
  llm_parameters: 
    max_tokens: 1000
    temperature: 0
  llm_prompt_template: |
    You are a trusted AI assistant that helps answer questions based only on the provided information. Here is some context which may or may not help you answer the following question: {context}.
    
    Answer directly, do not repeat the question. Based on this context, answer this question: {question}.
    
    If you don't know the answer, just say that you don't know.

  llm_prompt_template_variables: 
    - context
    - chat_history
    - question

input_example:
  messages:
  - content: What are the factors associated with greater banking sector outreach, and how do they impact firms' financing constraints?
    role: user
output_example: This is an example output