databricks_resources:
  model_name: "databricks-meta-llama-3-3-70b-instruct"
  vs_index_endpoint_name: "one-env-shared-endpoint-13"
  
retriever_config:
  index_name: global_fs.worldbank.chapter_index
  columns: 
    - chapter
    - chapter_text
    - footnotes
  parameters: 
    k: 1
  retriever_schema:
    primary_key: chapter
    text_column: chapter_text
    doc_uri: chapter
    name: databricks_documentation_vs_index

llm_config:
  llm_parameters: 
    max_tokens: 1000
    temperature: 0
  llm_prompt_template: "You are a trusted AI assistant that helps answer questions based only on the provided information. If you do not know the answer to a question, you truthfully say you do not know. Here is the history of the current conversation you are having with your user: {chat_history}. And here is some context which may or may not help you answer the following question: {context}.  Answer directly, do not repeat the question. Based on this context, answer this question: {question}"
  llm_prompt_template_variables: 
    - context
    - chat_history
    - question

input_example:
  messages:
  - content: What are the factors associated with greater banking sector outreach, and how do they impact firms' financing constraints?
    role: user